name: Build bootc disk image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request: {}
  schedule:
    - cron: "0 0 */2 * *"

env:
    BASE_IMAGE: ghcr.io/gbraad-dotfiles/fedora-bootc
    BASE_VERSION: 41
    IMAGE_NAME: fedora-workstation-bootc
    IMAGE_TAGS: 41 latest
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ github.token }}

    FULL_IMAGE_NAME: ghcr.io/gbraad-dotfiles/fedora-workstation-bootc:latest
    #DISK_TYPE: qcow2
    ROOTFS: xfs
    ARCH: amd64
    BIB_IMAGE: quay.io/centos-bootc/bootc-image-builder:latest

jobs:
  build-container:
    name: build-containers-bootc
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
    - name: Remove unwanted stuff
      uses: gbraad-devenv/remove-unwanted@v1

    - uses: actions/checkout@v4

    - name: Build image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ env.IMAGE_TAGS }}
        oci: true
        build-args: |
          BASE_IMAGE=${{ env.BASE_IMAGE }}
          BASE_VERSION=${{ env.BASE_VERSION }}
        containerfiles: |
          ./containers/Containerfile

    - name: Push to registry
      id: push-to-registry
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
        extra-args: |
          --disable-content-trust
        
    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-registry.outputs.registry-paths }}"


  build-diskimage:
    name: Build qcow2 image
    needs:
      - build-container
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Remove unwanted stuff
        uses: gbraad-devenv/remove-unwanted@v1

      - uses: actions/checkout@v4

      - name: Workaround podman issues in GH actions
        run: |
          # see https://github.com/osbuild/bootc-image-builder/issues/446
          sudo rm -rf /var/lib/containers/storage
          sudo mkdir -p /etc/containers
          echo -e "[storage]\ndriver = \"overlay\"\nrunroot = \"/run/containers/storage\"\ngraphroot = \"/var/lib/containers/storage\"" | sudo tee /etc/containers/storage.conf

      - name: Workarounds for GH runner diskspace
        run: |
          # use custom basetemp here because /var/tmp is on a smaller disk
          # than /mnt
          sudo mkdir -p /mnt/var/tmp/bib-tests
          # on GH runners /mnt has 70G free space, use that for our container
          # storage
          sudo mkdir -p /mnt/var/lib/containers
          sudo mount -o bind /mnt/var/lib/containers /var/lib/containers
          sudo mkdir /var/lib/containers/storage

      - name: Build prepare
        run: |
          mkdir -p ./output
          sed -e 's;@@IMAGE@@;${{ env.FULL_IMAGE_NAME }};g' config.toml.in > config.toml
          sudo podman pull ${{ env.FULL_IMAGE_NAME }}

      - name: Build image - qcow2
        id: build-image-qcow
        run: |
          sudo podman run \
            --rm \
            -it \
            --privileged \
            --pull=newer \
            --security-opt label=type:unconfined_t \
            -v ./config.toml:/config.toml:ro \
            -v ./output:/output \
            -v /var/lib/containers/storage:/var/lib/containers/storage \
            ${{ env.BIB_IMAGE }} \
            --target-arch ${{ env.ARCH }} \
            --type qcow2 \
            --rootfs ${{ env.ROOTFS }} \
            --local \
            ${{ env.FULL_IMAGE_NAME }}

      - uses: actions/upload-artifact@v4
        with:
          name: disk-amd64
          path: output/qcow2/disk.qcow2
          retention-days: 7

  push:
    name: Push image
    needs:
      - build-diskimage
    permissions:
      contents: read
      packages: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    container: 
      image: ghcr.io/gbraad-actions/fedora:stable
      options: --privileged

    steps:
      - name: Set release tag
        id: get-tag
        run: |
          echo "TAG=$(date +'%y%m%d')" >> $GITHUB_OUTPUT

      - name: Download amd64
        uses: actions/download-artifact@v4
        with:
          name: disk-amd64
          path: disk-amd64/

      - name: Prepare and compress disk image
        run: |
          mv ./disk-amd64/disk.qcow2 ./disk-amd64/machine.x86_64.qemu.qcow2
          zstd --rm -T0 -14 ./disk-amd64/machine.x86_64.qemu.qcow2

      - name: Wrap disk image in container
        run: |
          buildah manifest create machine-os
          buildah manifest add --artifact --artifact-type="" \
            --os="linux" --arch="x86_64" --annotation "disktype=qemu" \
            machine-os \
            ./disk-amd64/machine.x86_64.qemu.qcow2.zst

      - name: Login to ghcr.io
        run: |
          podman login ghcr.io -u ${{ github.actor }} \
            -p ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and push image container to registry
        run: |
          podman tag machine-os:latest ghcr.io/gbraad-dotfiles/fedora-workstation-bootc-disk:latest
          podman tag machine-os:latest ghcr.io/gbraad-dotfiles/fedora-workstation-bootc-disk:41
          podman tag machine-os:latest ghcr.io/gbraad-dotfiles/fedora-workstation-bootc-disk:${{ steps.get-tag.outputs.TAG }}
          podman push ghcr.io/gbraad-dotfiles/fedora-workstation-bootc-disk:latest
          podman push ghcr.io/gbraad-dotfiles/fedora-workstation-bootc-disk:41
          podman push ghcr.io/gbraad-dotfiles/fedora-workstation-bootc-disk:${{ steps.get-tag.outputs.TAG }}
